### ISSUE TITLE
Put %n back because everyone who said it was non-standard is stupid

### ISSUE THREAD

**Issue by WillEccles** [WillEccles/cfm#18]
Everyone said it was non-standard, well guess what idiots, [C99 standard](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf) 7.19.6.1 section 8 disagrees with you >:D

cfm got all slow and memory-inefficient because I actually listened to people on the internet, why did I ever do that?

**Comment by E5ten** [comment]
Since all the uses of %n in cfm seem to be at the end of the format string, couldn't you instead use printf's return value (which, on success, is the number of characters printed)? e.g.:
```c
printf(" %zu/%zu%n", n ? s+1 : n, n, &count);
```
would become
```c
count = printf(" %zu/%zu", n ? s+1 : n, n);
```

**Comment by WillEccles** [comment]
I might do this, though not because of the Android thing. Android is in second place on the list of operating systems that cfm is not targeted at, following Windows, but in the interest of portability I suppose I could do this. A much better reason to do this is reducing the runtime of printf.
