### ISSUE TITLE
Shorten $HOME to ~ in pwd

### ISSUE THREAD

**Issue by willeccles** [willeccles/cfm#26]
Copy how promptus does this (or don't)

**Comment by rutrum** [comment]
Hi willeccles.  I am new to programming in C and would like to tackle this issue.

**Comment by willeccles** [comment]
@rutrum Hi David. Unfortunately, I already fixed this in the dev branch, and probably should have closed this issue :( I would also say that if you're new to C this is arguably the worst program you could work on just given how unholy the code is written, what with being one file and all. However, if you see any of the other issues you'd like to work on, or you come up with any ideas for cfm, I'm all ears and will accept PRs and am willing to help clarify things if you're having issues with the code.
