### ISSUE TITLE
Terminal (Alacritty) not cleared

### ISSUE THREAD

**Issue by zuixalias** [WillEccles/cfm#33]
When i open shell in the current folder/ exit cfm, the previous text is not cleared and the current text (the text after exiting/ opening a shell) overlaps with the previous one.

(Works fine with `xterm`)

**Comment by sophec** [comment]
I will have to reinstall Alacritty to test this. However, I did almost all of the development of cfm originally in Alacritty, so this would be a new one.

**Comment by zuixalias** [comment]
Here is a [video](https://mega.nz/file/h8NABL5I#tlrl8iisQMFhhZVyltfs8R-gDZHXcn_Ysy_DoLi-XS0), if it helps.
(The terminal is Alacritty)

**Comment by zuixalias** [comment]
There is one more thing related to gui update:

What happens:
- Got an error somehow
- I create/ edit a file/ folder or do any task involving a text editor
- I save the changes and quit the editor OR quit without saving.
- The error message is still there

Expected:
- The gui should update when using some command/ starting or finishing a task...so error msg should not be there.

(Btw, it's fine if it was intended)
