### ISSUE TITLE
File/ Dir does not delete sometimes

### ISSUE THREAD

**Issue by zuixalias** [WillEccles/cfm#35]
When i try to delete a file/ directory using `dd`, cfm says `The dir/ file already exists` or `Error deleting: File exists`, then i have to keep pressing `dd` till it deletes (it eventually does delete, on the third try).

**Comment by zuixalias** [comment]
I forgot to mention that it happens once in a while with a new `cfm` instance, and right now not fully sure if it deletes on the third everytime.
Also, there is another error: `No such file or directory` when deleting...this one occurred when i created a file, deleted it, then recreated and then tried to delete.
Though it happens only sometimes, other times it's works fine.

(So i assume it could be related to the file system instead of cfm as such...idk though)

**Comment by sophec** [comment]
Do you have multiple instances of cfm running? They will all share the backup directory used for deleting files and they will each start counting deleted file IDs from 0. If you delete a file in one cfm instance and then in another without closing them in between, they will both try to create a deleted file with the same name.

**Comment by zuixalias** [comment]
Most probably no...just to be sure i will keep on using cfm making sure that only one instance runs, if i encounter any deletion error then i will post here.
Earlier i didn't think that other instances could be running, but just before you posted your reply i enountered an error again: `Error deleting: File exists`..then i read your reply and checked in htop, no other instance was running.
(This error occurred after i opened a file using `e` then exited the editor and tried to delete) (i tried replicating but it was fine when i did)

**Comment by zuixalias** [comment]
<del>
UPDATE:
`Error deleting: File exists` when trying `dd` on a folder.
- Only one cfm instance was running
- The error seemed random (i.e., not specific to any path/ file type) and up till now has occurred only in a fresh instance and exactly once. (Though i haven't deleted as much files/ folders from a new instance so cannot be sure if it could occur again in the same instance)

I will now reboot my PC so that i can fully confirm that only one instance was running.
(This is because if the crashes due to other script issue could have done something, though highly unlikely but anyways)

---

UPDATE 2:
Before posting this i ran `cfm` again and did the following:
- Created  a new file, kept the default name, saved it, and exited the editor back into cfm.
- Tried to delete the created file and the same error (the one mention above in this msg), but now to delete the file i had to press `dd` 4-5 times.
Note:
- It's the same if i just quit the editor, which keeps the default file name.
- It's the same error for both, files and folders. 
- **It occurs almost everytime when i create a new file/ folder.**

This one seems to be easy to replicate..i am getting it almost everytime of the times i think.

---

UPDATE3:
There is a pattern. After i create a file/ folder, i am unable to delete it until i press `dd` 5 times (could be one up or down)...but after i am done pressing `dd` the said number of times, it works normally.
I can either exhaust all the presses on a single file/ folder OR i can create new ones and try to `dd` them till i react the limit (which is around 5, as mentioned above).

Conclusion: In a new instance of cfm, i must press `dd` atleast around 5 times (tried again and it goes up to 10) on a file/folder to delete it...after that it works fine.
</del>

**Comment by zuixalias** [comment]
Yes, the issue i think is of multiple instance (not exactly though, more like improper exit by the user/ if killed by the user)...if i exit cfm using the i3 config `kill` shortcut (which i use to exit apps), it seems that cfm somehow keeps running (seems unlikely since it's not visible in htop) or most probably is unable to execute the *on_exit* code or something like that.
So on next run, the behaviour mentioned in the msg above is seen which i think is due to the way `dd` command is handled.

**Comment by zuixalias** [comment]
From https://i3wm.org/docs/userguide.html :
> 2.5. Closing windows
> 
> If an application does not provide a mechanism for closing (most applications provide a menu, the escape key or a shortcut like Control+w to close), you can press $mod+Shift+q to kill a window. For applications which support the WM_DELETE protocol, this will correctly close the application (saving any modifications or doing other cleanup). If the application doesn’t support the WM_DELETE protocol your X server will kill the window and the behaviour depends on the application.

So yea, seems like the issue is because some exit code is not executed when terminal is closed directly, before closing cfm that is.

**Comment by sophec** [comment]
Yeah, this is out of scope of cfm. Closing the terminal without quitting cfm is not something I can support or handle.

**Comment by zuixalias** [comment]
Can you add a exit handler for SIGKILL...i tried it on cfm (via htop) and it seems to be the trigger of the error (90% of the times atleast).

**Comment by sophec** [comment]
No. From `signal(7)`:

> The signals SIGKILL and SIGSTOP cannot be caught, blocked, or ignored.

If you could catch/ignore every signal, there would be no way for you to stop a process which didn't want you to stop it. Long story short, if you forcefully quit a program, there's nothing you can do about it not having time to clean up after itself.

**Comment by zuixalias** [comment]
Alrighty, then i assume i would need to modify the command on my side...thanks for the info!

**Comment by zuixalias** [comment]
Umm, i tried SIGINT, SIGTERM, SIGKILL on the terminal...it seeems that if the terminal is closed directly then irrespective of the signal, there is something up with the exit handling.

Please do look into it whenever you got time.

(Basically cfm keeps running after the terminal is closed directly) (Also, even if i close the running instances and then attempt to delete the file, the error still pops up)

**Comment by sophec** [comment]
All of the above behavior is dependent on several things, and cfm is not one of them. i3, your terminal, and possibly your shell (if it's using it here) are in charge of this. cfm does not receive the signal. The signal is delivered to your terminal, which can then (optionally, and not at all in the case of SIGKILL) pass it on to the shell (if one is running) or cfm before handling it for itself. There's nothing I can do about a use case which involves suddenly terminating the program or its controlling terminal. If you don't require undo functionality, you can use <kbd>alt+dd</kbd> to delete files permanently.

**Comment by sophec** [comment]
To be quite frank, I don't have much time to work on this anymore and it's just a hobby project I made years ago. The code is a mess (pretty intentionally; that was part of the fun), it's not particularly stable or well-designed, etc.

I use it as a tool to browse files and sometimes edit them, but that's about it--I have probably used it to actually *manage* files a total of 10 times in the last few years. Unfortunately, the proper refactor and C++ rewrite are unlikely to be finished any time soon (if ever), so for the time being it's a bit Spartan and broken. If you're intending to use it daily as a proper file manager, I'd recommend looking elsewhere (or using a GUI one, since they're generally pretty good at their jobs).

That said, I appreciate the support! If you want to continue using cfm I will support you as I have time to, but do be prepared for some bugs. If looking for an alternative, I'd recommend vifm. If you're familiar with vi(m), you'll find it comfortable to use. There are plenty of others, however.

But I must stress that this particular issue is mostly the fault of the environment combined with the way cfm does backup/undo. Without redesigning how that works, this is an unfortunate side effect. If I ever do get around to finishing the C++ rewrite, it should be much more stable and reliable.

**Comment by zuixalias** [comment]
Ahh, i see...ok. I understand you bro, no problem.
Anyways, i am glad that such a project exists. A neat little thing! Just on point for me...

Alrighty, do as you find best. I will keep in mind your recommendations.
Catch ya later! Byeee
