### ISSUE TITLE
Add an option in config.h to set the cfmtrash dir

### ISSUE THREAD

**Issue by MrLazerbean** [WillEccles/cfm#6]
It might be better to put it in the cfm directory by default instead of having it clutter up the home folder.

**Comment by WillEccles** [comment]
I was going to add this option at some point. However, there is no "cfm directory," so I don't know what you mean. I was actually considering something in the /tmp directory by default. Will take a look on Monday.

**Comment by WillEccles** [comment]
Implemented in 2cdc6c014ba675342b27d83e5aec781b259cd9fd.
