### ISSUE TITLE
After opening a file using xdg-open, cfm becomes locked up and will not accept imput, aside from "Enter"

### ISSUE THREAD

**Issue by MrLazerbean** [WillEccles/cfm#7]
Video for clarity

Basically if you open an image file using xdg-open once you leave the file shortcuts like h, j, k, l, dd, q, and the like wont work. Instead, they will just type the letters over the filename that is selected. The only way to fix the issue I have seen is to open the file in $EDITOR, exit out of the file, and the keybindings will be back. 

EDIT: Seems to only happen on .jpg and .png files now, NOT other file types. 
https://youtu.be/eiKY9uxPdIg

**Comment by WillEccles** [comment]
Can't reproduce.
