### ISSUE TITLE
Delete function no longer works in newest release

### ISSUE THREAD

**Issue by MrLazerbean** [WillEccles/cfm#8]
The dd and D commands no longer work to delete files in the newest release of cfm. If you try to delete files the error "Error deleting: Invalid cross-device link" appears. This does not happen on older builds of cfm.

**Comment by WillEccles** [comment]
That is because your /tmp is not on the same partition as the file you are trying to delete. This is because "deleting" is actually copying to a temp directory. Not sure the best way to deal with this yet. Specify a working temp directory using the `$CFM_TMP` environment variable.

**Comment by WillEccles** [comment]
I think the only good way to fix this is to finish a copy function first. Working on that next.
